mozilla/wpt-sync

- sync/bug.py
- sync/downstream.py
Also add a note that the bug will be auto-merged. This is for better
compatibility with Gecko triage processes.
> Set bug priority as P3 on creation.

- sync/upstream.py
> Add PR link when commenting on Bugzilla for failing upstream checks.

- sync/notify.py
- test/test_notify.py
Make it clearer that new tests that don't pass aren't passes when skimming.
> Slightly improve the results notification message.

- sync/downstream.py
In particular we have requests to make it clearer what the lifecycle
of the bug is, and to make it clearer who made the upstream
change. This rewrites the bug message so that the purpose of the gecko
bug is explicitly stated, and the parts from upstream are added as
quotes with an author attribution taken from the upstream commits.
> Make the bug message more informative about what's going on.

- sync/upstream.py
We apparently get multiple messages for failures, so only update the
bug if the commit or status has changed. Also only update the last
status if we actually add something to the bug because we might get an
overall status of failed and multiple pending, and if we update the
overall status to failed before we actually add a message to the bug
then we won't actually add the message when all jobs are complete.
> Only message on failed checks if the status changed.

- sync/landing.py
- test/test_landing.py
We need to exclude all files that either shouldn't be in m-c at
all (e.g. .git) or have modifications in m-c that we want to
preserve (e.g. LICENSE, where we explicitly mention the BSD variant
and vendor specific override files).
> Exclude some files when copying wpt over

- sync/downstream.py
This is typically unhelpful since we aren't running all tests in this
case. Therefore there are two possible scenarios:
* Some tests should be affected, but we don't know which ones, so we'd
have to run all tests to find out which actually are and make the
correct metdata update.
* No tests are supposed to be affected, and any changes are an
error (or intermittent).
We run all tests before landing anyway, so the first case is covered
on that path. For the second case a human really needs to examine the
changes to ensure that nothing untoward has happened. In any case
there's no point in generating metadata that should never change anything.
> Don't update metadata when no tests are affected by a PR.

- sync/landing.py
The copy-based approach was adding .git files from submodules to the
working tree and although these weren't checked in they would appear
in the manifest. This change ignores .git files anywhere. However,
it might be worthwhile considering moving to using git ls-tree to get
a list of actual paths to copy over.
> Don't sync .git files/dirs anywhere in the tree.

- sync/landing.py
If we are trying to cherry-pick metadata and get an empty commit, we
currently error out. There are two possible ways to handle this;
either pass --allow-empty and so end up with a meaningless commit, or
handle the error and continue without making a commit. The latter
seems preferable in terms of not having useless commits in the
history, so we do that here. Unfortunately it's a little fragile since
we depend on the error message string to determine what happened.
> Handle empty metadata commits.

- sync/update.py
If we have a try push then we want to run through the try push update
process when running the pr command to ensure that if it completed
then we update the sync as appropriate (e.g. by marking it as
metadata-ready).
> Update the latest try push status from wptsync pr

- sync/downstream.py
This was happening and causing crashes.
> Handle the case where the pr body is None

- docker/start_wptsync.sh
Also, don't allow many containers to run celery: if a
pid is found, we abort the start-up of services so a
human may decide what they really want to do.
> Only clean pid before starting worker (#108)

- sync/bug.py
- sync/commit.py
- sync/downstream.py
This sets the URL field of the bug to the PR URL for convenient access
> Set bug URL for downstream PRs.

- sync/listen.py
Whenever the wptsync service falls over, we get a broken-pipe
socket error originating in the listen_forever code.
At the same time, rabbitmq reports that the client closed
the TCP connection, so what we've been calling "rabbitmq falling over"
actually seems to be our pulse listener falling over. Retrying
the consumer connection is my naive attempt to make this go away.
> Retry Pulse consumer connection on socket.error

- sync/update.py
When running the manual updating code for a PR that is closed, we
shouldn't use a status event, because the status is no longer
relevant. Instead we should run the event corresponding to the most
recent action on the PR. This is notably different in the case that
the PR was merged despite a failing status check; without this change
we simply fail to generate metadata for such a PR from the `wptsync pr`
or `wptsync landable --all --retrigger` commands.
> Update closed PRs using an appropriate PR action

- sync/listen.py
ConsumerMixin takes care of reviving dropped connections.
See https://github.com/celery/kombu/blob/v4.1.0/kombu/mixins.py#L35
> Refactor Pulse listener to use kombu's ConsumerMixin

- sync/landing.py
When landing commits we need to find the appropriate sync. Typically
we identify upstream syncs from the bugzilla-url field in the
metadata, but unfortunately there's at least one case where this is
missing. To deal with this, we make a last-ditch effort to find the
sync by parsing out the bug number from the message if no sync could
be found by any other means.
> Add an attempt to identify the sync for an upstream commit by message.

- sync/downstream.py
Always call update_commits before next_try_push. In update_commits,
unset the error flag if we are successful. Then if we are not
successful, we never end up with a try push (and we can explicitly
check for that condition to be sure). This prevents the case as with
PR 10536 where we have a merge conflict and then get some event that
causes a try push anyway.
> Don't push to try if a downstream sync has an error.

- sync/notify.py
This was missed when implementing this.
> Fixup notification code for taskcluster changes.

- sync/command.py
- sync/landing.py
This allows repushing to try if an infra bustage or similar affected the results.
> Add a retry option to wptsync landing.

- ansible/roles/wptsync_host/defaults/main.yml
- ansible/roles/wptsync_host/tasks/main.yml
- bin/provision.sh
- bin/update_server.sh
- docs/deployment.md
- requirements/deploy.txt
I noticed a new error with update_server.sh after updating ansible. This PR fixes that and proposes other minor improvements for consistency. 🐮 <-- closest known emoji to a yak
> Improve deployment scripts

- sync/landing.py
The block was indented one level too deep
> Fixup replacing Bug None in commit messages.

- sync/landing.py
This will be required to allow pushing to inbound.
> Add MANUAL PUSH annotation to commits

- sync/bug.py
- sync/downstream.py
This has a small hack to work around a Bugsy bug that we can fix asynchronously.
> Correctly set bug statuses to reopened.

- sync/downstream.py
This is the most supported by bugzilla.
> Truncate bug summary at 255 characters

- test/test_landing.py
#403 #379 
Added a test where an upstream gecko bug has changes made to it in the wpt pr (such as fixing a minor bug to be able to merge it upstream), and ensure that those new changes are landed back into Gecko, but not the original upstreamed commits as they haven't changed.
> Created an extra test for relanding upstreamed PRs

- sync/upstream.py
- test/test_upstream.py
[WIP]
This property is to get the commits of a WPT PR that is related to a Gecko Bug. It tries to use the local wpt git repository as much as possible, and falls back to using the GitHub API if something is inconsistent.
> Added a `pr_commits` property to UpstreamSync

- sync/landing.py
During landings we try to rebase the changes on top of the integration
branch a couple of times. When this fails we need to be sure to add
notification in the bug so that someone knows to fix it manually.
> Ensure we comment on landing bug when rebases fail

- sync/command.py
If there's an ongoing landing, start looking for new landable commits after the head that
landing will update to
> Handle ongoing landing better in wptsync landing|retrigger

- sync/downstream.py
This can happen because all the logs have expired, which then causes
the sync to get blocked. We really want a better solution here that
will allow us to actually generate a results notification in that
case, but not blocking the syncs is at least a priority
> Don't raise an error if try_notify fails to download logs

- sync/downstream.py
- sync/gh.py
https://paste.mozilla.org/LCBhptWp
Also ensure proper handling in situations where we try to remove a label from an issue that doesn't have it.
> Added check to ensure pr_id is converted to int

- sync/downstream.py
The idea of rebase_apply is that if the commits in the PR depend on
things that have landed on inbound after the PR was created, we rebase
onto inbound and the commits should them apply. But this function was
buggy and only handled the case where we had already applied some of
the commits to gecko, not the case where the first wpt commit had
conflicts. In the latter case we basically want to hard reset head to
inbound and then try to apply again.
> Make rebase_apply work when don't have existing gecko commits

- sync/bug.py
Apparently the Bugzilla REST API doesn't allow setting comments and adding flags
at the same time. That's annoying because the Web UI can do this, but apparently uses
a custom endpoint. Anyway to stop things failing, special case the comment handling.
> Fix setting comments in BugContext

- sync/bug.py
> Add a separator if there is text in the whiteboard already

- sync/upstream.py
> Set landed status after existence of PR is determined

- sync/handlers.py
> Check a try push's taskgroup ID for None or errors

- sync/notify/wptfyimsg.py
- sync/wptfyi.py
The HTTP endpoints for this changed a little, so update the code to match.
> Fix getting metadata

- sync/sync.py
- test/config/sync.ini
- test/conftest.py
- test/test_landing.py
- test/test_sync.py
- test/test_upstream.py
Since inbound is going away we now have to push to autoland instead
> Update to land on autoland

- sync/bug.py
- sync/landing.py
Use this to set the landing sync to block all bugs for PRs that will
land with that sync.
> Add the ability to set depends_on and blocks for bugs

- sync/landing.py
When adding the metadata commits for landings, use the metamerge merge
tool to try to automatically resolve conflicts in ini files. Note that
git mergetool falls back to an interactive mode in the face of
deletions, which isn't what we want here, so avoid calling it in those
cases.
> Use the metamerge mergetool when adding metadata to landings

- config/gecko_config
This was forgotten when we moved to autoland
> Update pushurl in gecko config.

- ansible/roles/wptsync_host/tasks/main.yml
- config/wpt-metadata_config
- docker/start_wptsync.sh
- docs/deployment.md
Fow now I've pointed this at a fork of that repo to ensure that things
work correctly before pointing at the main repo.
> Configure the wpt-metadata repository

- sync/bug.py
- sync/downstream.py
> Ensure attachment data is encoded as UTF8

- sync/command.py
- sync/downstream.py
Make it accept multiple PRs and simplify the handling of the --force flag
> Improve the wptsync notify command a little

- sync/handlers.py
I have a feeling this is a typo
> Fix typo in transaction parameter

- sync/downstream.py
- test/test_downstream.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1605350
> Add SKIP_BMO_CHECK message to commits we're pushing to try

- sync/base.py
- sync/bug.py
- sync/handlers.py
- sync/lock.py
- sync/meta.py
- sync/notify/__init__.py
- sync/notify/bugupdate.py
- sync/tasks.py
- sync/upstream.py
- sync/worker.py
This is based on https://github.com/mozilla/wpt-sync/pull/586 so not suitable to merge yet.
> Automatically update metadata for bug changes

- sync/bug.py
- sync/notify/bugs.py
- sync/upstream.py
- test/test_notify_bugs.py
We started filing some bugs in layout components, and this raised a few issues around the bug metadata and text. This is a first cut at fixing those issues.
> Fix some problems related to filing bugs

- sync/handlers.py
- sync/listen.py
- sync/update.py
> Revert "Check for taskgroup completion when tasks finish"

- sync/landing.py
Otherwise these cause the mergetool to hang
> Handle added by [them|us] merge conflicts.

- sync/command.py
- sync/update.py
This changes the output to be a little bit more useful in the common case. It also adds `--rebase` to `wptsync retrigger`
> Make some improvements to `wptsync landable`

- sync/commit.py
- sync/landing.py
This should help ensure that we don't have a bug that causes us to drop commits.
> Add some additional asserts when conmputing the commits to land

- docker/Dockerfile.dev
as discussed, as I have no idea how emacs works. :)
> Install vim into the Docker container

- sync/meta.py
This records the error in new relic for diagnosis, but otherwise
allows the sync to continue.
> Don't error if a metadata update fails

- sync/bugcomponents.py
This happened a few times and it's hard to diagnose. Also
it possibly shouldn't be fatal.
> Improve error reporting when the moz.build update fails

- sync/update.py
The pr id is some globally unique thing that we don't care about
> A pr id is not a pr number

- README.md
Fix typos at the end of README.md ("Note" section)
> Correct typos on README.md

- sync/projectutil.py
- sync/repos.py
This now happens automatically and the command has been removed.
> Remove calls to create-mach-environment

- sync/base.py
- sync/bug.py
- sync/command.py
- sync/commit.py
- sync/downstream.py
- sync/gh.py
- sync/index.py
- sync/landing.py
- sync/listen.py
- sync/notify/msg.py
- sync/projectutil.py
- sync/sync.py
- sync/trypush.py
- sync/wptmeta/__init__.py
- test/conftest.py
> Remove remaining uses of six

- sync/base.py
- sync/index.py
- sync/sync.py
- test/test_downstream.py
- test/test_upstream.py
We sometimes run into a problem where we've created the data for a sync, but for whatever reason we don't complete creating the indexes or branch references for the sync.
To solve this, refactor sync creation so that things happen as follows:
* Create the branches. These do not themselves create a sync, and they are easy to update/remove if necessary.
* Create a single commit with the sync data and the initial indexes for the sync.
The latter change requires that we pass a CommitBuilder in to the SyncData and Index creation functions. This will add the data to the same commit, and will finally cause the commit to happen once we exit the outermost "with" block.
This also requires that we're able to construct the indexes without already having a SyncProcess object. So the make_key functions …
> Make sync creation more atomic

- sync/downstream.py
- test/test_downstream.py
> Try to rebase downstream sync when error occurs

- bin/provision.sh
> Copy config file during deployment

- .github/dependabot.yml
This should cause the uv.lock file to be updated
> Set dependency ecosystem to uv

- bin/provision.sh
- pyproject.toml
- uv.lock
Without these changes, the provision script can not find `ansible-playbook` command
> Fix provision script
