mozilla/wpt-sync

sync/command.py
sync/handlers.py
sync/update.py
sync/upstream.py

This is mostly for the transient initial case where we assume that we are up to date with
upstream on central. But we probably actually aren't so in this case we want to allow
running upstreaming over some larger range of commits. Because the base commit isn't
in the normal pulse message we get, we smuggle the base commit though a _wptsync field
when invoking the handler from a command.

Allow setting the initial commit for the wptsync upstream command.

---

sync/upstream.py

If we override the last sync point for wptsync upstream it's possible
to end up in a situation where the revision we sync to is earlier than
the current last sync point. In this case we don't want to update the
stored last sync point or we will accidentally redo work.

Don't update the last sync point if it would make it earlier.

---

sync/gh.py
sync/update.py
sync/upstream.py

This avoids the problem where we misuse the status API and think that
something has failed when it hasn't. We also add better logging for
the failing case.

Use combined upstream status checks when checking if we can merge a PR.

---

sync/base.py
sync/upstream.py
test/test_landing.py
test/test_upstream.py

We had a bug in out handling of backouts that meant we were creating a new sync for the backout, which wasn't expected. To fix this we have to ensure we look at the syncs for commits that were fully backed out, and also ensure we don't lose data when changing the sync status.

Fix handling of upstream sync that are backed out

---

sync/command.py
sync/landing.py

It makes sense to be able to control which wpt commit we land up to
from the command line, so this adds a --wpt-head argument to wptsync
landing that does just that.

Allow passing in the target commit for a landing

---

sync/base.py
sync/downstream.py
sync/gh.py
sync/update.py
sync/upstream.py
test/conftest.py
test/test_downstream.py
test/test_upstream.py

The sequence of GitHub status events that trigger handlers.handle_status
can sometimes include many "success" statuses. We don't want to
report success for each such event, only for the overall success of all
checks. We can do this by requesting combined status from the GitHub
API every time we see a non-"pending" status event.
Similarly, when downstreaming, we should only trigger a try
push once the combined status is "success".

Use combined PR status to determine success. (#16)

---

sync.ini
sync/downstream.py
sync/gh.py
sync_prod.ini
test/conftest.py
test/testdata/sync.ini

This isn't supposed to happen, but it's a belt-and-braces approach to fixing an observed
problem. The idea is that by throwing an error we can figure out how to stop the code getting
this far.

Don't allow downstreaming when the moz-wptsync-bot created a PR.

---

sync/downstream.py

Otherwise we end up warning about the results for tests that probably
weren't actually affected by the PR. In the future we may want to
notify in some other way for these things.

Don't generate results notifications for PRs with no affected tests.

---

sync/upstream.py
test/test_upstream.py

Note that this must land after the changes to the way that remotes are stored in #32

Delete remote branch when upstream sync merges

---

sync/upstream.py

Simply always try to land all open PRs that don't have errors.

Simplify the logic about when to try and land PRs during upstreaming.

---

sync/commit.py
sync/landing.py
test/test_landing.py

When reapplying commits that we upstreamed but won't be involved in
the landing, only apply the parts that touch web-platform-tests,
ignoring other gecko changes.
Unfortunately git-cherry-pick doesn't provide a mechanism to pick a
partial commit, so instead we reuse the same show/apply machinery as
for moving commits between different trees, with the difference that
we amend the previous commit and use a three-way merge since the
history is meaningful.
The patch also makes resuming in the middle of a landing work better;
if there's an error during apply one fixes it up in the normal way
then runs git commit --amend -F <sha1>.message and reinvokes the
landing code to continue.

When landing only reapply parts of patch that touched wpt.

---

sync/landing.py
sync/trypush.py
test/test_landing.py

This wasn't happening because we were accidentially checking if the
metadata already existed on the sync rather than on the landing, which
of course it did.
Also bundle in a few other minor fixes for landing issues.

Ensure we actually move metadata over during landings.

---

sync/landing.py

We currently have the wpt submodules checked into the tree, so in the
interests of conservatism, retain that behaviour.

Update wpt submodules before landing.

---

sync/bug.py
sync/landing.py
test/test_landing.py

If we are reappling upstreamed commits to a landing and we get some
kind of git error, we need to fix it by hand and then reinvoke the
landing code. When we do this, we *only* want to reinvoke applying
upstreamed commits for the HEAD of the repository, otherwise we end up
trying to reapply patches to whatever does happen to be the HEAD
irrespective of which PR it is or whether it's a metadata commit.
This also contains a small optimisation so that we only recompute the
set of unlanded commits if we are actually going to use them. It
should also be possible to store that in the process data, but we
would need to ensure that the data is invalidated by a rebase.

 When rerunning a landing, only reprocess prs that are at HEAD.

---

sync/downstream.py

When the `last_pr_check` hasn't changed, we don't perform any new
operations on the sync so there's no reason to unset any previous
sync error status.

Only unset sync error status if we're updated the sync (Fixes #64)

---

sync/landing.py
test/conftest.py
test/test_landing.py

The previous approach to non-synced files didn't actually work because
the patterns were only matched against the filename and not the full
path. Also the files were deleted because we didn't restore the copy
from the current gecko tree.
In this new approach we match the full path for all the files with a
custom ignore function, and use git checkout_index on the gecko side
to ensure that the files are later restored.

Fix up the handling of non-synced files.

---

sync/downstream.py
sync/landing.py

This ensures that the worktree exactly matches the index, including
for removals. Using the underlying git command is recommended by the
gitpython author.

Use git add --all for updating metadata.

---

sync/landing.py
test/test_landing.py

Ensure we create only a single commit inclusingn any additional
metadatta updates and the change in the in-tree sync point.

Clean up commits created during landing.

---

sync/downstream.py
sync/upstream.py

The upstreaming code was accidentially trying to re-upstream stuff
that itself came from upstream. This patch checks if the commit has
metadata indicating that it came from upstream, and if it does we
filter it out of the commits considered for upstreaming.

Don't try to upstream commits resulting from a landing.

---

sync/downstream.py
sync/update.py

If for some reason we happen to crash out after creating a PR but
before creating a bug, we can end up with a bug that has no PR. In
that case we want to allow creating such a bug when running the
wptsync pr command (assuming that the PR didn't get closed in the
meantime).

Enable creating a bug as part of the sync pr command.

---

docker/gecko_config

This enables landings to actually push to inbound.

Add a push url to the mozilla repo config.

---

sync/command.py
sync/downstream.py
sync/update.py

If we have a backlog of PRs it can be helpful to do a landing and then retrigger all the unlanded ones because some will be blocked on something that is now fixed (e.g. some intermittent error or a merge conflict that's now resolved). This adds a --retrigger option to `wptsync landable` that attempts to do this.

Add ability to automatically restart incomplete syncs

---

sync/commit.py

I believe this provides the most useful behaviour in terms of conflict handling,
even if there isn't actually the right information to do a real three way merge.

Make three-way merge the default.

---

sync/command.py
sync/landing.py

This is helpful in catching up with a backlog of PRs that could build
up for various reasons. The metadata update will all happen in the
landing, so it does have the disadvantage that we won't detect or
disable unstable tests or get per-PR metadata, so it's a method of
last resort, but it can nevertheless be useful.

Add an option to include incomplete syncs when landing.

---

sync/downstream.py
sync/landing.py

We were previously using the bug number for the landing itself for the
commits from each PR. But that doesn't make much sense; we should use
the bug for the corresponding sync.

Use sync bug as the bug number for landing commit.

---

sync/command.py
sync/downstream.py
sync/landing.py

This causes the sync to not be required to have metadata before
landing the correesponding PR. This can be useful if the sync puts the
repo into a broken state, or is low-value but happens to have an
error, or similar.

Add a skip attribute to downstream syncs

---

sync/landing.py

Sometimes we are lacking a bug number when we make metadata commits
for whatever reason. Since we can't actually land anything with "Bug
None" at the start of the commit message, check for that case and add
a valid bug number from the sync or the landing.

Handle missing bug number in metadata commits.

---

sync/base.py
sync/downstream.py
sync/update.py

After wpt commits are either merged or fast-forwarded onto master the
range origin/master..origin/pr/<id> is empty since the endpoint is an
ancestor of the master branch. Instead we should take the commits that
actually landed onto the master branch explicitly, setting the base
commit to whatever the commit prior to landing was.
The way we handle updating the base commit is non-ideal since it has
to be set in the sync data and then updated in the CommitRange
object. However this should be enough to fix the problem we currently have.

Update wpt commits correctly after a merge

---

sync/downstream.py

This is basically reverting back to a looser check before making  a try push.
Initially the comparison with last_pr_check was added to prevent
unnecessary bug updates on repeated "success" status, but in
retrospect I don't think this is necessary for downstream syncs:
the only way we update the bug in case of "success" is to flip
the whiteboard error field if it's not already None, and we don't make try pushes
unless the PR commits change.

Make a new try push whenever we get new commits and PR status is success (#74)

---

sync/downstream.py
sync/gh.py
sync/handlers.py
sync/trypush.py
test/test_downstream.py

There's no point in doing all the work of a stability run if the PR is
undergoing active changes. It will save resources at the possible cost
of some latency to only schedule this once it's marked as approved.

Wait for PR approval before scheduling a stability run.

---

docker/Dockerfile.dev

The regression we were avoiding has been fixed and the old version
stopped being avaiable to install, so this seems like a good time to
update.

Update to the latest git cinnabar

---

README.md
ansible/roles/wptsync_host/templates/run_docker.sh.j2
bin/run_docker_dev.sh
docker-compose.yml
docker/Dockerfile.dev
docker/rabbitmq.conf
docker/start_wptsync.sh
docs/user-guide.md

With these changes, `docker stop -t 60 <container>` will give celery and rabbitmq a chance to shutdown gracefully. The entrypoint script also attempts to clean up stale pid files when starting up.

Add clean-up to entrypoint script

---

sync/handlers.py
sync/update.py

Before this we would not do anything for a merged PR where the HEAD of
the PR changed since we last updated

Handle open and merged prs in the same way during update.

---

sync/base.py

Previously we were logging too early so it looked like we were always
renaming the ref to the same name. We also want a safety check that
we don't do that since we could end up deleting a valid reference.

Fix logging of reference rename and add safety check.

---

sync/commit.py

This should ensure that the author is preserved when upstreaming.

By default preserve author when moving commits.

---

sync/gitutils.py
sync/handlers.py
sync/upstream.py
test/test_landing.py
test/test_upstream.py

I think this is required because there's a synchronisation delay between mozilla-unified and
the source repos. We want to deal with unified, but the events we are getting are based on the
source repos, so the commits haven't necessarily appeared when we run the handlers.

Add facility to wait for a specific gecko hg rev to appear when updating repos.

---

sync/commit.py
sync/landing.py

The copy-and-reapply approach was running into some bugs, so in order
to expediate getting landings working disable this for now. In theory
it's a good idea because if limits the possible drift from upstream,
but in practice we have had difficulties ensuring that we always
reapply the correct commits.

Apply all landing commits by diff rather than copy

---

sync/base.py
sync/bugcomponents.py
sync/downstream.py
sync/landing.py

If we did a landing where not all the upstream PRs had corresponding
metadata changes, we need to ensure that the moz.build metadata is
updated right before landing, or we will break the build. So factor
this code out and run it right before landing as well as during the
individual metadata updates.

Run the moz.build metadata update during landing.

---

sync/downstream.py
sync/landing.py
test/conftest.py
test/test_downstream.py

PRs that are later reverted cause unnecessary work since the revert
won't apply until mozilla/central is updated with the original commit,
which is presumbably broken in some way. Instead of figuring all of
this out, it makes more sense to just skip both the original PR and
the reverting PR, assuming that they overall have no effect.
Putting this code at the start of  update_commits is not ideal, but it
must certainly run before that method since it will typically fail if
the revert doesn't apply to central.

Mark syncs for PRs that are reverted, and the reverting sync as skip

---

sync/upstream.py

If the backout has a previous sync but that's been merged we want to reuse that bug number.

Fix getting a bug number for upstreaming backouts.

---

sync/command.py
sync/handlers.py
sync/trypush.py

We really only care about complete vs not complete for statuses, so use that
and avoid having try pushes go from a status of complete to infra_fail

Make infra_fail a property of try pushes rather than a status.

---

sync/downstream.py
sync/handlers.py
sync/upstream.py

The previous change introduced a regression so that we didn't handle
status updates to PRs we created. This fixes that and ensures that the
merge sha is actually passed into the handler.

Fix handling of PR status updates.

---

sync/landing.py
test/test_landing.py

Otherwise we forget to do it in cases where we do the try run manually.

Update sync point before landing to try.

---

sync/base.py
sync/commit.py
sync/upstream.py
test/test_upstream.py

This allows us to avoid reprocessing commits that have already been
processed, which can happen e.g. with manual intervention. The sync
data is stored in a git note associated with the gecko commit.

Store sync associated with commit in upstream sync.

---

sync/base.py
sync/command.py
sync/downstream.py
sync/handlers.py
sync/landing.py
sync/update.py
sync/upstream.py
sync/worker.py
test/test_landing.py
test/test_upstream.py

Also, handle backouts of landings by ensuring that the relevant
landing is set to "open" and marked as having an error. Togehter this
means that we can't start a new landing until the present
one reaches central and any backout that happens before that will
prevent a new landing from starting.

When a landing reaches central mark as complete and trigger the next one

---

sync/landing.py

When we fail to cherry-pick metadata changes, we then try to reset any
changes to files not corresponding to tests. For files that exist on
master that amounts to a checkout, but for files that don't we should
remove the changes.

Handle unneeded changes to metadata files that were deleted on master.

---

sync/commit.py
sync/landing.py

Don't duplicate metadata, and ensure that there is a blank line before the
metadata.

Fix formatting of landing commit message.

---

sync/base.py
sync/downstream.py
sync/handlers.py
sync/landing.py
sync/tc.py
sync/trypush.py
test/test_downstream.py

This is a tentative PR. I don't have a full picture of the impact on landing code, so would like some initial feedback on whether the overall approach makes sense. 
The rough idea is to mark a sync with "error" if we try to get metadata from an empty try push (no wpt tasks) -- this can happen if tasks expire from taskcluster, which they do after 28 days, or if the decision task failed.
The other piece is to create a try push again during downstreaming if we know the previous one was an infra failure. 
Also note to self before I run out the door: todo - check wpt_tasks in next_try_push, force True.

Account for infra failures when creating or using try pushes.

---

sync/bug.py
sync_prod.ini

This gets them off triage radars.

Self-assign new bugs.

---

sync/downstream.py
sync/gitutils.py
sync/landing.py
test/conftest.py
test/test_downstream.py

If we have a downstream sync and new commits are added, we currently
just add those commits after any existing metadata update commit. This
means we can break later invariants that there is only a single such
commit, or simply not apply the metadata during landing. Instead we
remove the metadata commit before updates, and reapply it later. Since
applying the upstream commits may fail, we need to store this pointer
in the sync data.

Ensure that the metadata commit is the tip of downstream sync

---

sync/gh.py
sync/upstream.py
test/test_upstream.py

After a backout we were closing the PR, then pushing, then trying to
reopen the PR later. But that doesn't work; GitHub reequires that you
keep the branch the same as the point at which the PR was closed until
after you reopen it. Also we seemed to be missing the code to actually
reopen the PR.

Fix upstreaming after a backout

---

sync/commit.py
sync/downstream.py
sync/errors.py
sync/gitutils.py
sync/landing.py
sync/tasks.py
sync/trypush.py
sync/update.py
sync/upstream.py

Introduce a RetryableError class which is used to wrap exceptions
which can be retried automatically. Enable automatic retries for
selected exceptions, notably:
* Failing to fetch a given commit when updating repositoires
* Tree closures

Enable retries for specified exceptions.

---

sync/downstream.py
test/test_downstream.py

Gecko's hg hooks reject commit messages with try: in them. It turns out that Chrome uses
similar syntax but allows it in commits, so we end up with this case being hit
semi-regularly.

Handle try: in downstream commit message.

---

sync/base.py
sync/update.py

I think `update_status` should have probably been removed as part of this change: https://github.com/mozilla/wpt-sync/commit/98dd4953eeddddcf37f536adf9215edbd48a5376#diff-5de2e9e8eca6903bae6547b8990e75ff
I ran into a TypeError when running `wptsync update` as a result -- the empty base update_status method was being called:
```
[2018-05-22 19:55:13,606] ERROR:sync.tasks:update_status() takes exactly 4 arguments (3 given)
[2018-05-22 19:55:13,607] ERROR:sync.tasks:Traceback (most recent call last):
File "/app/wpt-sync/sync/tasks.py", line 41, in inner
return f(*args, **kwargs)
File "/app/wpt-sync/sync/command.py", line 262, in do_update
update.update_from_github(git_gecko, git_wpt, sync_classes, kwargs["status"])
File "/app/wpt-sync/sync/update.py", line 217, in update_from_github …
```

Remove empty, unused update_status method.

---

sync/landing.py

Since all pushes to central are merge commits, using first_parent means that we don't
process any of the commits being merged in, and so don't notice landings being
completed.

Remove first_parent from git log when handling pushes to central.

---

sync/downstream.py
sync/handlers.py
sync/landing.py
sync/listen.py
sync/notify.py
sync/tc.py
sync/update.py

The handling of decision tasks previously contained a few bugs,
notably that we were assuming the statuses were in the
taskcluster-queue set, but actually the pulse message we are using
here is from treeherder, which has two different kinds of status,
"state" which is just about whether the job is complete and "result"
which is about whether it succeeded, and a different set of
corresponding strings.
In addition the handling of failed decision tasks was lacking; we were
immediately failing and complaining in the bug, but not retriggering
anything. Now we attempt 5 retriggers before giving up.

Fix the handling of decision tasks.

---

sync/downstream.py

This is wallpapering over the real problem which is that sometimes we miss the
relevant commits, presumably due to an incorrect base. But it does prevent us erroring out.

Enable creating downstream bugs if commit set is empty.

---

sync/commit.py
sync/downstream.py
sync/landing.py

Previously we fixed this for try push messages only. The string try: is not allowed
in hg.mozilla.org commits since it can be confused for a try message. But it's relatively
common in Chromium commits. We need to ensure it's removed when creating a landing commit.

Ensure that try: doesn't appear in landing commit messages.

---

sync/landing.py
sync/trypush.py
test/test_landing.py

The current design was predicated on the idea that metadata from PR
try runs would usually be accurate enough that metadata updates
wouldn't be required on landing. But in practice this doesn't seem to
be the case. Given that, the disadvantage of the previous approach is
that end up retriggering many hundreds of jobs on each push, and the
resulting metadata update causes problems like poor performance and
OOM due to the number of logs being consumed.
A simple switcharound implemented here is, assuming the first try push
fails, to do a metadata update without any retriggers and perform a
new try push. If that try push also fails, we fall back to the current
approach of retriggering failed jobs to check for intermittents.

On landing, do a try push with metadata updates but without retrggering.

---

sync/upstream.py

Otherwise we can lose stuff that should be upstreamed but was bsacked out if the post-backout
commits end up with a merge conflict (because we won't typically look for errors in incomplete
upstream syncs, but will in open ones).

Reset sync status to open before trying to update commits.

---

sync/command.py
sync/update.py

By default we don't rebase when updating PRs, but we may want to do so
where it will fix a conflict (in the future we may wan to make this the default)

Add a command line option to allow rebases from wptsync pr.

---

sync/landing.py
test/test_landing.py

These aren't supposed to be different from the clang builds.

Exclude msvc from fuzzy builds.

---

sync/landing.py
test/test_landing.py

These are smaller and can now be used as the basis of metadata updates.

Use wptreport.json files for metadata updates.

---

sync/tc.py

The route is the key thing here; I think deleting it was just a mistake.

Ensure that retriggers appear on Treeherder.

---

sync/upstream.py

This was creating bugzilla noise when some optional jobs failed.

Ignore status changes for prs relating to merged upstream syncs

---

sync/landing.py

Otherwise the command can start a new landing prematurely or try to re-push an old one.

Make wptsync landing check if the current landing is on inbound/central

---

sync/commit.py
test/test_commit.py

This will garble any commits that are testing non-UTF8 encodings.

Don't send patches through a UTF8 encode/decode step

---

sync/bug.py

Hi there! I have just realized that the Sync Bot suddenly started to file bugs on Bugzilla [without a bug type specified](https://bugzilla.mozilla.org/buglist.cgi?bug_type=--&reporter=wptsync%40mozilla.bugs). The `type` field is currently optional, but we’ll soon [make it required](https://bugzilla.mozilla.org/show_bug.cgi?id=1562364). Let’s use the “task” type for all new bugs.

Specify “task” bug type when filing a new bug

---

sync/downstream.py
test/config/sync.ini

We can't use the checks API until we migrate to use a GitHub app, so
allow it to be disabled in the settings to prevent the log spam from
it always failing.

Make GitHub check subject to a config setting

---

sync/commit.py
test/test_commit.py

In some cases we can end up with multiple clashing metadata strings in
a single commit message. We know that the metadata we added for that commit
is always at the end, so prefer metadata at the end of the commit.

Prefer metadata at the end of the commit message

---

sync/downstream.py
sync/landing.py

We run --update-intermittents with stability try pushes so that things
which have multiple runs with differing results end up marked as
intermittent with multiple statuses in the metadata. In order to handle
the possibility of old base commits with the previous --stability option
we look in the help output for the required options before using them.

Use multiple statuses to handle intermittents where possible

---

sync/landing.py
sync/upstream.py
test/test_landing.py

#379 
Added a test that replicates a potential scenario where this would arise:
1 - Create a pull request to wpt that is unrelated to Gecko and merge it
2 - Create a Gecko bug, upstream it, and merge this PR into wpt unchanged.
3 - Land the wpt changes into try/central
The LandingSync returned at step 3 should only have the PR from step 1 going into try, as it would have identified step 2's commit being from a Gecko bug and not even bothered trying to apply it.

Don't try to reland upstream PRs if the commits didn't change.

---

sync/bug.py
sync/commit.py
sync/upstream.py

This encourages authors to investigate when their PRs fail to merge
which should avoid some of the problem where we have many PRs that are
not merged fo rtrivial failures or need to manually ping authors.
This adds the beginnings of a new API for working with bugs that
allows making multiple changes before updating bugzilla, so that the
needinfo request and the comment come from a single conceptual place.

Support adding needinfo when upstream PR can't merge

---

sync/upstream.py

#377 
The issue here seemed to be caused by the code that is in charge of posting the merge comment in bugzilla doesn't then block off that execution path and will in theory re-post the comment agian and again if requested. 
#371 
Here the status of the sync was moved to "complete" without any check to notify bugzilla that the merge had been made. This meant that if update_github was called before the entry point update_pr, it would mark the sync as "complete" and update_pr would never notify bugzilla via comment. Checking the state of the sync before marking as "complete" should be enough to determine if we need to post a comment. 
Note: This will likely need a refactor later to the way status transitions and notification is handled, but for the time being these two changes should …

Stop repeating merge comments & stop race condition causing no merge comment

---

sync/downstream.py
sync/trypush.py

Previously we checked if all tasks were a success before running the
metadata update steps. But the weaker condition of "are any jobs
actually failing" makes more sense because only failing jobs might
have logs that will result in a metadata update, and we are already
allowing the possibility that jobs don't run (leading to a status of
exception or similar) earlier in the function.

Only download logs from try if some tasks actually failed

---

sync/downstream.py
sync/gh.py
test/test_downstream.py

#378 
This will add a label to the GH PR if something goes wrong with the downstream sync process and an error is stored. Technically this error property can be set by something other than an error happening in Gecko so maybe a different name for the label is needed?

Add a github label when there is a downstream error

---

docker/Dockerfile.dev

#394
We seem to have intermittent failure when running `sudo apt-key adv ...`. One way to mitigate this and hopefully less often have to manually restart builds is to retry the command if it fails, and if it  fails a certain number of times then we fail the build. 
[Here](https://travis-ci.org/dhdavvie/wpt-sync/jobs/569397682#L1708-L1735) is an example where the command failed twice, but finally on the third attempt it passed.

Retry apt-key command on travis if it fails

---

sync/landing.py
sync/worker.py

#218 
By setting the retry value to something other than 0, `apply_async` no longer hangs and will raise an `OperationalError` in a test environment due to it not being able to resolve the broker hostname. In theory this should work on production but we should keep an eye on the logs to see how it comes along.

Try to retrigger failed tasks after push to gecko

---

sync/bug.py
sync/upstream.py

When adding a needinfo check the flags for an existing similar-looking
needinfo request, and when adding a comment using the BugContext
frontend, perform a similar check that we aren't posting duplicate content.

Avoid adding duplicate comments and needinfos in some cases

---

sync/downstream.py
sync/gh.py
sync/handlers.py
sync/upstream.py
test/test_upstream.py

This functionality seems to be missing. By checking the 'merged_by' user we can see if the bot has merged the PR, and report back to BMO. Extended a test to also check this comment gets posted.

Check if the bot has merged a PR and comment on BMO

---

sync/landing.py
sync/trypush.py
test/test_landing.py

pgo ccov and msvc builds no longer exist, but shippable builds are slow and
can be excluded from the PR runs.

Update test types run on try

---

ansible/roles/wptsync_host/tasks/main.yml
config/gitattributes

This ensures that the ini files are automerged in as many cases as possible
and prevents merge conflicts blocking landings. The only problem is that
the mergedriver has to live in the worktree for operational reasons, so
we have to fall back to the standard mergedriver in cases where it fails
e.g. because it can't be found.
The patch ensures that when we provision the host machine we add the necessary
git config to the gecko repository using the  commands, and set the
correct attributes simply by copying over the attributes file.

Configure git to use a custom mergedriver for ini files where possible.

---

sync/bug.py

Relic logs shows a high error rate at the moment to do with getting 0 length responses from BMO. Doing a broad except and raising retryable error. Maybe should be catching ValueError specifically for this?

Handle bmo errors

---

sync/bug.py

This was causing invalid requests.

Ensure we don't send multiple copies of the flags field to bugzilla

---

sync/base.py
sync/command.py
sync/commit.py
sync/load.py
sync/sync.py

By default just delete the newest matching object, and add a command
line option to instead delete all. Also fix some API misuse trying to
delete try pushes and clean up the repeated code a little.

Make wptsync delete command more useful

---

sync/landing.py
sync/trypush.py
test/test_landing.py

This is needed to enable testing aarch64 builds which run on central but not usually on try.

Use full task set for running landing try pushes

---

sync/sync.py
test/test_upstream.py

This means that in cases where the error has a visible effect like in
the GitHub labels we never end up with finished syncs.

Ensure error flag is unset when a sync is finished.

---

sync/upstream.py

A small UI improvement would be to set the status of the github commit checks to `success` when we see that gecko has landed. 
Example: https://github.com/web-platform-tests/wpt/pull/18789
The downstream patch landed, but this is not reflected in the check. Would be nice if this weren't the case so we could more easily identify a successful merge.

Update GH commit status when gecko landed

---

sync/projectutil.py

#466
The output of recorded Newrelic log seems to be truncated due to length. This should hopefully provide us with a field to see the relevant information about the error.

Record CalledProcessErrors better with newrelic, continue raising.

---

sync/bug.py

The error handling here caused some unnecessary exceptions; make it more
lenient in case we have code that sets and unsets the comment or something

Handle missing comment field in bug.

---

sync/downstream.py

This can happen if we accidentially broke the command. Just assume that nothing is
affected in this case.

Handle wpt tests-affected failing.

---

sync/landing.py

If the previous try push was complete but had infra fails we want to start a new
try push. And in the case that action is required, be more specific about what
can be done

Improve handling of complete try pushes when running wptsync landing.

---

sync/projectutil.py

This prevents the cache becoming a space leak, and avoids a somewhat
common error we've seen with the cache becoming corrupted. The reasons
for this are unclear, but the performance implications of simply not
using the cache are well within the bounds of what's reasonable to get
a simple fix.

Remove .mozbuild wpt cache

---

sync/downstream.py
sync/gh.py
sync/handlers.py
sync/trypush.py
test/conftest.py
test/test_downstream.py
test/test_landing.py

With the current implementation, the bot can spam the try server with try pushes from an upstream PR (see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1573920)). In some cases with the Chromium export bot, it also pushes stability try runs because the upstream PR is already approved but still receiving changes from the downstream Chromium repo. 
By removing the initial try push entirely and only pushing a stability run once the PR has been merged, we can reduce a significant amount of spam and save on cost. The trade-off is turn around time of the sync, but this should not be that significant.
Here I've changed `next_action` to go straight to stability run on pr merged, and the same has been done in `LandingSync.next_try_push`. Log downloading has been changed to handle stability …

Remove initial try push & push stability once PR is merged.

---

sync/landing.py

Previously we only marked the try push as complete once the results
had been used and subsequent actions like rebase had been
completed. But that meant that a failure in those subsequent actions
caused the metadata to get re-updated.
Instead mark the try push as complete right after completing the
metadata updates, and ensure that subsequent runs of the code don't
repeat the metadata update for a complete try push.

Change the sequencing of marking landing try push as complete

---

sync/command.py
sync/downstream.py

For syncs that already have a non-stability try push but require a stability try push,
ensure we schedule one. Also improve the error messages for manual_fixup cases a little.

Ensure we don't get stuck with non-stability try push

---

sync/landing.py
sync/trypush.py
test/test_landing.py
test/test_try.py

Use this to implement a fisson query that more closely matches the mochitest central
configuration.

Enable passing multiple arbitary queries to mach try fuzzy

---

sync/downstream.py
sync/tc.py
sync/trypush.py
test/conftest.py
test/sample-data/taskcluster/taskgroup-complete-build-failed.json
test/sample-data/taskcluster/taskgroup-no-tests-build-failed.json
test/test_downstream.py
test/test_tc.py

If we have build failures, we should notify the bug. We should also not flag the try push for manual fix if we have some builds and subsequent tests that completed. 
Should also add build failure notification in `try_notify` but will probably do that in another PR.

Weaker infra failure conditions, notify on build failures

---

sync/downstream.py

Before we were creating the notification after the non-stability try push.
But now we want to create it after the sync is ready to land

Ensure we don't create notification before try push is done

---

sync/downstream.py
sync/sync.py
sync/trypush.py
test/test_downstream.py

Now that we only do try pushes after the PR has merged, the idea of
expiring too-old try pushes doesn't make sense. This was also already
a bit broken since the expiration of the try push shouldn't matter
once we've started a landing, but we weren't considering that.

Remove the concept of expired try pushes

---

sync/landing.py
sync/trypush.py
test/test_landing.py
test/test_try.py

Previously we could exclude downloading logs for intermittent tests
because we didn't handle multiple results for the same test well. But
with --update-intermittents, we really want to download all the
logs. So remove the exclude list from the final metadata update.

Don't exclude logs from metadata update for landing

---

sync/downstream.py
sync/landing.py
sync/notify/geckomsg.py
sync/trypush.py
test/test_landing.py

These are giant and we now always use wptreport.json instead

Remove support for downloading raw logs

---

.travis.yml
requirements/prod.txt

It seems as though the change to the Xenial distribution of Ubuntu as
the default distribution for Travis made our tests run slower. This
should resolve that issue by locking the Ubuntu version to the Trust
version.
(Also more_itertools seems to have become a dependency due to locking the version)

Use Trusty Ubuntu distribution to speed up tests

---

sync/tc.py

This needs to be deployed after gecko actually moves, which afaik is Nov. 9th.

Update to new gecko Taskcluster URL

---

sync/meta.py
sync/repos.py
sync/wptmeta/__init__.py
test/config/sync.ini
test/conftest.py
test/test_metadata.py
test/testdata/wpt_metadata_config

wpt-metadata is a repo containing YAML files. Since we already have
good support for working with git repos, it makes sense to expediate
our ability to edit this data by supporting direct reads and writes
from the repository rather than needing to go via a wpt.fyi API.
The write support is designed to commit changes lazilly. This means
that we should be able to avoid text-based merge resolution by running
an algorithm where we pull the latest version of the upstream, apply
our edits, and then push. If the push fails due to conflicts we pull
again and retry.
So far this isn't wired up to any users in the repository; it will
eventually be used to support filing bugs for untriaged failures, and
for ensuring that the triage data is kept up to date with bugzilla
changes.

Add support for accessing wpt-metadata repo directly

---

sync/trypush.py
test/test_try.py

This platform is very capacity limited and Tier2 so we should be less worried about intermittents there.
To improve our e2e time, don't do multiple retriggers on that platform but just use a single result.

Quick hack to stop retriggering aarch64 jobs

---

sync/tc.py
test/conftest.py

When migrating to the new taskcluster, I forgot that we still needed read access to the
old taskcluster for try jobs that have already run. This patch adds a check that a given taskId
is accessible on each TaskCluster instance before deciding which queue or index to use.

Support getting data from old TaskCluster

---

config/dev/sync.ini
sync/bug.py
sync/command.py
sync/landing.py
sync/upstream.py
sync_prod.ini
test/config/sync.ini
test/test_landing.py

Don't abort early in case we have a complete try push, and ensure that
in the case of error we always add a comment to the bug so that it's
clear something has gone wrong.

Improve the error handling for updating try pushes after landing.

---

sync/landing.py

Since upstream syncs have already landed, so it doesn't make sense to block them

Set landing sync to only block downstream syncs

---

ansible/roles/wptsync_host/tasks/main.yml
config/gecko_config

The previous setup as a mergedriver didn't work well since the tool should only
be used in some cases but not all. This approach is a good start but does require
extra code (not implemented) to use the mergetool at the correct times

Configure metamerge as a mergetool

---

sync/landing.py
sync/trypush.py
test/test_landing.py

Presumably in this case we already accepted the failures when the
retriggers were scheduled. Of course this could break if it happens
that someone manually retriggered some jobs, but that seems like a
smaller risk.

Don't mark failures as unacceptable if there are retriggers

---

sync/bug.py

This reverts commit ab21115122e62217624f522ea3a040392fc069ab. This
turns out to not be supported on bmo.

Revert "Allow creating bugs with markdown comment"

---

docker/Dockerfile.dev

forgot to add the flag to enable the listener in the Dockerfile. Could also have the phab listener started by default with the `--worker` flag

Enable Phab Listener

---

sync/phab/listen.py

The custom events aren't showing up in Insights, reading the documentation it seems to be because it is missing application context according to this: https://docs.newrelic.com/docs/agents/python-agent/python-agent-api/record_custom_event
Hopefully this should fix it

Add NR application context to custom event

---

sync/bug.py
sync/bugcomponents.py
sync/downstream.py
sync/meta.py
sync/notify/bugs.py
sync/notify/results.py
sync/wptmeta/__init__.py
test/test_landing.py
test/test_notify_bugs.py

This is the initial phase of this work and will probably initially only be turned on for `Testing :: web-platform-tests` components. For other components I may add some in-tree metadata that determines what to do for each component so it can be self-serve.

File bugs for failing tests

---

sync/handlers.py
sync/tc.py
sync/update.py

This prevents a number of errors we experience when the decision task fails. It doesn't quite provide the optimal solution to the problem which is to rebase and start a new try push (since usually a failed decision task is a problem in the gecko code).

Better handle failed decision tasks

---

sync/notify/bugs.py

This can happen if all the results were handled in a previous step

Handle empty test results for notification

---

sync/base.py
test/test_base.py

There's a general confusion in the codebase about whether
obj_ids (i.e. PR numbers and bug numbers) are represented by integers
or strings. In ProcessName objects they are always strings, but
sometimes in other contexts they aren't. This warrants a general
solution, but there was a specific problem with lookups in the
ProcessNameIndex passing in an integer obj_id and not finding
anything, so force the type to be str inside the get() function.

Ensure that all lookups in ProcessNameIndex are done with strings

---

sync/phab/listen.py

These events were identified by the newrelic events. This should
cover most of the events.

Handle more phabricator events

---

sync/worker.py

We aren't seeing logging to sync.ini, presumably because the celery logging setup
isn't interacting well with our setup. Try just disabling all the celery setup

Try preventing celery setting up its own logging.

---

sync/update.py

Previously we always got autoland. Also we don't really care about inbound any more

Fix getting repo for wptsync push command

---

sync/command.py
sync/gitutils.py
sync/handlers.py
sync/update.py
sync/upstream.py

When pushes to autoland were rare and we didn't need to push to
autoland it made sense to optimise this out. Now it doesn't
any more

Always fetch from autoland when updating repos

---

sync/upstream.py

We hit a case where we were getting a merge conflict and for some reason
the process continued. This clearly doesn't always happen, but add an
extra assert to help debug next time

Assert the wpt checkout is clean after applying commit

---

sync/notify/bugs.py

In cases where multiple subtests were in the results we were passing in the
same test_id many times, making for more slowness in the commands

Don't pass same test id to test_ids_to_paths multiple times.

---

sync/downstream.py
sync/landing.py
sync/sync.py
test/test_downstream.py

The gecko_rebase() function previously forgot to set the
gecko-base property of the sync, so the commit range would
end up being too large. This only mattered in practice when there
were other wpt-sync commits on autoland, but not on central.
Change things so that when we do the rebase we always set the new base.
There is still a failure mode where the rebase fails and we don't
manually redo the rebase, so the stored base would end up as
autoland rather than central, but the actual base would be central.
Even in this pathological case it's pretty unlikely that anything
actually bad will happen; the worst cas scenario is that there are
commits on central that haven't been applied to autoland that look
like part of the sync.

Set gecko_base when doing gecko_rebase

---

sync/landing.py
sync/trypush.py
test/test_landing.py

This does two things:
* Passes --disable-target-task-filter from Bug 1618633, which means
that we select all the jobs that might run on central, including
things that are not part of the default try set, but not things
that are only on try for experiments.
* Updates the try selector to reflect the fact that the above change
handles fission, the devedition jobs no longer exist, and we only
need to run shippable builds on linux32 (since those are the only
builds in that configuration).

Update try strings for landing pushes

---

sync/downstream.py

We need to check for infra_fail before we check for tasks, because
an infra fail that prevented the decision task from running can
mean that we have no taskgroup_id.

Handle try push with no tasks and infra_fail

---

sync/notify/msg.py

It seems like there's an occasional issue where we fail to get result statuses in the summary
and we call max() on an empty sequence. It's not quite clear how this happens, but we can at least
avoid throwing in that case.

Don't fail if we didn't get any result statuses in the summary

---

sync/downstream.py
sync/gh.py
sync/meta.py
sync/notify/bugs.py
sync_prod.ini
test/conftest.py
test/test_notify_bugs.py

We were previously doing metadata updates by pushing directly to
master in (a fork of) the wpt-metadata repository. However because the
repo has CI checks that must pass before merging PRs to ensure that
the data is valid we actually want to create a PR first. This adds an
(optional) PR creation step when writing metadata.

Create PRs when pushing to wpt-metadata repo

---

sync/notify/results.py

The code to get the baseline logs for central assumed that it
could get the central push using the merge-base of the commit with
central. But this doesn't work in the case where the sync was
rebased onto autoland and autoland merged into central. In this
case the merge-base will be the tip of autoland at the point where
we did the rebase, and that isn't usually a push head from central.
Instead we need to take the merge-base and ask hg what the central
push containing that commit was. Happily that's almost exactly the
same as code at [1] so the implementation can be mostly copied.
[1] https://searchfox.org/mozilla-central/source/testing/web-platform/manifestdownload.py#74

Use push to central for base of logs, not merge-base

---

docker/Dockerfile.dev

This isn't doing anything useful so there's no need to run it.

Don't start phabricator listener

---

sync/base.py
sync/downstream.py
sync/notify/bugs.py
test/test_notify_bugs.py

This makes the process more idempotent as we can rerun it without refiling
bugs in the same components

Store the bugs that we file during notifications

---

sync/handlers.py
sync/listen.py
sync/update.py

There is a failure mode we've encountered where we get some builds failing,
and the resulting taskgroup doesn't complete until all the unscheduled tasks
time out a day later. But we want to handle that case upfront, as soon as we
can know that the remaining tasks aren't going to run.
To do this, we process all tasks rather than just decision tasks. When a
non-decision task completes, we load all the tasks from the taskgroup and
check for completeness ignoring anything that's unscheduled. This has some
performance cost, so we are careful to only look at tasks we scheduled
ourselves.

Check for taskgroup completion when tasks finish

---

sync/bug.py
sync/notify/bugs.py
test/test_notify_bugs.py

This doesn't make sense since the sync doesn't actually handle them.

Don't assign notification bugs to sync

---

sync/landing.py
sync/trypush.py
test/test_landing.py

This will make this try push slower, but avoids breakage caused by artifact builds
not working, which happens quite often

Don't do an artifact build for final try push

---

sync/landing.py

This itself invokes mach so we need access to the state directory

Ensure we set MOZBUILD_STATE_PATH when invoking mergetool

---

sync/gh.py
sync/upstream.py

GitHub doesn't automatically dedupe identical status checks, and we can end up
hitting limits if we don't get the status before setting it

Get status before trying to set it

---

sync/update.py
sync/upstream.py

has_metadata assumes that it's being called with a commit message that's
represented as bytes. UpstreamSync.from_pr also called it with a PR body
that's Text. Add the relevant type annotations and ensure we pass in bytes.

Ensure has_metadata is called with bytes

---

sync/listen.py
test/sample-data/taskcluster/decision-task-success-pulse.json
test/sample-data/taskcluster/test-task-success-pulse.json
test/test_listen.py

We only want to set the taskgroup id from successful decision tasks.
Handling these in both the try-task handler and the decsion-task
handler means we end up setting the taskgroup id even when the
decision task failed, which then means we have the wrong
taskgroup id and can't download the test results

Only handle decision tasks with the decision task handler

---

sync/commit.py
sync/landing.py
test/conftest.py
test/test_landing.py

The previous patch failed to consider two cases:
* Upstream syncs which typically (but not always) don't result in a
patch to gecko.
* Downstream syncs for changes that were also applied
to gecko (this happens sometimes when people don't want to wait for
the sync)
This fixes the two cases as follows:
* For upstream syncs it counts the number of such syncs and adds that
number to the relevent assert.
* For downstream syncs it ensures that there's always a commit even
if it's empty. This commit will be removed later when we rebase
onto autoland.

Fix the asserts when checking we have all commits in a landing

---

sync/downstream.py

That means the comparison will always fail since both sides are now integers

Don't convert pr name to string for comparison

---

sync/bug.py

This isn't actualy supported by bugzilla

Don't send cc_detail field when creating bugs.

---

docker/Dockerfile.dev
requirements/py2.txt

That's required for git cinnabar. We pin the version to 5.4.x because
release cinnabar doesn't yet support 5.5.x

Ensure mercurial is installed under python2

---

sync/bug.py

Otherwise we can't convert it to JSON

Ensure attachment data is text

---

sync/gh.py

This returns a 404 for reasons I don't understand (maybe
permissions). But the data we need is returned in the branch response,
it's just that pygithub doens't expose it. So use the raw_data to get
at it.

Don't try to get the branch protection endpoint

---

sync/upstream.py

This check is currently using the upstream branch, which can be deleted after a
merge. We could change it to use the local record of the commit, but it doesn't
seem that useful to add complexity rather than just moving the setter to after
the merge check.

Move setting PR status to after the check on whether it merged.

---

docker/Dockerfile.dev

It might now work to remove Python 3.6, but this is a more minimal change for now

Update to Python 3.7

---

sync/trypush.py
test/conftest.py
test/test_downstream.py
test/test_landing.py

Before we were still running the fission disabled configuration. Now that those have `nofis` in the job name, we were failing to run any try builds at all.

Enable running fission on try

---

sync/trypush.py

These will still get run as part of the final landing.

Don't try TSAN builds for downstream syncs

---

requirements/prod.txt

4.0.0 breaks Celery; the fix will be in the next Celery release

Downgrade billiard to 3.6.4.0

---

sync/landing.py
test/test_landing.py

When landing PRs that came from mozilla-central we check if the are upstream commits are identical to the ones we already pushed, because we know there's no point in re-applying those.
One of the codepaths uses the reflog to check if the upstream commits are the same as any previous head of the PR branch. But it's not guaranteed that a reflog exists for a branch. In particular for very old branches it may have been gc'd. gitpython doesn't handle that situation very well, and raises an exception which suggests a bug.
We can handle that exception and just fallback to the code which assumes that the commits may have changed (even though this is likely to generate a merge conflict that has to be handled manually).

Handle the possibility of a missing reflog

---

sync/bug.py

Closes #706 
In the scope of the bug:
- added an option to force update information about the bug from Bugzilla
- used the force option to get fresh information, when we get whiteboard tags, so when the bot tries to add bot specific tags it has updated state.
Not sure, if I can write a test here, since a lot is mocked here.

Fix the issue with bot reverting the whiteboard tags

---

requirements/prod.txt

Revert "Bump billiard from 3.6.4.0 to 4.1.0"

---

.bandit
sync/.bandit

[The New version of bandit ](https://github.com/PyCQA/bandit/releases/tag/1.7.5) introduces [a new check for requests missing timeouts ](https://github.com/PyCQA/bandit/pull/743). 
For now, I've just skipped this, but happy also add the actual timeouts.
Also moved the `bandit` settings file to the source folder. According to [this issue](https://github.com/PyCQA/bandit/issues/698#issuecomment-811720709), this is the way to make it actually apply.

Skip "bandit" "request_without_timeout" issues

---

sync_prod.ini
test/config/sync.ini

The format of needinfo user settings was changed in the scope of [this PR](https://github.com/mozilla/wpt-sync/pull/573).
And then in [this PR](https://github.com/mozilla/wpt-sync/pull/709) it was reverted for production.
We will try first with non-wpt sync email addresses to see if fixing configs will make it work.

Fix needinfo user settings in prod and test configs.

---

sync/downstream.py
test/test_downstream.py

We can't call try_rebase in a non-@mut context because it mutates the PR. In particular this means we can't call it from next_action(), which is intended to be an idempotent method that describes the next action required for a sync, but doesn't actually carry it out. In practice this causes a runtime error when we attempt to update the sync state to indicate the problem.
This is a quick fix to unblock the sync, that is intended to be replaced with a better fix. Here we hardcode the logic that if the rebase succeeds, we need to do a stability try push. That relies on the assumption that for downstream syncs the only kind of try push is a stability one, which isn't true in the code (but is in practice). Ideally after the rebase calling `next_action` again would return the right result …

Quick fix for try_rebase failure

---

README.md

As discussed, this PR adds the link to the document in google doc to README.

Add the link to google doc with documentation to README

---

test/test_notify_bugs.py

unittest.Mock got an _lock attribute to synchronise access to the Mock in multithreaded cases. Unfortunately this clashes with our use of _lock on syncs to ensure we don't allow more than one process to mutate a sync at once.
For the cases where we're mocking whole Sync objects in tests, just overwrite the _lock class attribute with another mock; this seems to be enough for the tests to pass again.

Handle _lock on Mock objects

---

sync/downstream.py

I couldn't really reproduce it with tests, but it seems like the most logical place where it could loop in [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1849778) and [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1848752).

Do not invalidate the try push when there are no gecko_commits in the downstream sync

---

config/newrelic.ini

I've noticed the error about it in the New Relic agent log, it should correctly reapply it to the right one, but since we have this error there is no message about connection and no logs (there are logs until Sept 12), so maybe it's not correctly applied.

Update deprecated New Relic setting

---

sync/tc.py

Since the try logs require about 8Gb of disk space to reduce the chance of running out of space, we should clean up logs earlier.

Remove try logs after 3 days without activity instead of 5

---

sync_prod.ini

We were defining taskcluster-try-exception.* twice, which prevents the sync starting. We should define one queue for execeptions reported to the decision task and one -wptsync queue for exceptions reported for the overall try taskgroup.

Fix confusion between different exception queues

---

sync/meta.py
sync/notify/bugupdate.py
sync/notify/results.py
sync/wptmeta/__init__.py
test/conftest.py
test/test_metadata.py
test/test_notify.py
test/test_notify_bugs.py

Previously we only correctly handled metadata entries which had a "url" key, which generally speaking labels do not. In practice that meant we failed to notify for test changes in directories with labels.
This change adds a specific type to represent labels and ensure that they're correctly roundtripped through the update process.
This matches the data representation used in other tooling, but we will still need to update the code if a new kind of metadata is added.

Handle labels in META.yml files

---

docker/start_wptsync.sh

We already have [a logic to clean up a stale pid file](https://github.com/mozilla/wpt-sync/blob/master/docker/start_wptsync.sh#L83) when starting a container, but the pid file for a worker has a wrong name now because we don't provide a node name anymore, which is used in the name of the pid file.
Closes #2109.

Specify the node name to the celery worker

---

docs/deployment.md

Interestingly, I didn't find the existing documentation about sync.ini update (and `WPT_CONFIG` variable), only about credentials.ini, so here I added the info of what is happening now.

Update deployment documentation to add information about config update

---

.github/workflows/ci.yml

There is no available build of python 3.7 for the latest Ubuntu version in the Github actions.
See https://github.com/mozilla/wpt-sync/actions/runs/13328758853/job/37227831844?pr=2451.

Update python to version 3.8 in CI job

---

sync/downstream.py

At the moment, we run `mach file-info` with `testing/web-platform/tests <actual files which changed>`. Which worked fine [until recently when `file-info` command was fixed to work with files inside the directory (if it's specified)](https://bugzilla.mozilla.org/show_bug.cgi?id=1963319), since then it started to return all the bug components inside `testing/web-platform/tests` and the bot started picking a wrong component. To identify the right component, we don't really need to specify `testing/web-platform/tests` folder. This PR tries fixing this behavior.
From what I could track, it starts happening when parsing a string received from `wpt files-changed` we get an extra empty string and later down the chain we add `testing/web-platform/tests` prefix.
It's already tested and fixed on …

Remove empty pathes from changed files

---

docker/Dockerfile.dev
docker/start_wptsync.sh

It's somewhat unclear why setting UV_PROJECT doesn't help here, but in testing it seemed to be ignored (whereas passing in --project worked).

Run commands from the /app/wpt-sync directory
